services:
  - type: web
    name: studentportal
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn notes_project.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.14.0

databases:
  - name: studentportal-db
    databaseName: studentportal
    user: studentportal
